version: '3.4'
services:
  erigon.avado.dappnode.eth:
    build:
      context: ./build
      args:
        VERSION: v2.32.0
    image: 'erigon.avado.dappnode.eth:0.0.2'
    restart: always
    volumes:
      - 'data:/home/erigon'
    environment:
      - NETWORK=goerli
      - EXTRA_OPTS=
    ports:
      - '30303:30303'
      - '30303:30303/udp'
volumes:
  data: {}
