version: '3.4'
services:
  erigon.avado.dappnode.eth:
    build:
      context: ./build
      args:
        VERSION: v2.32.0
    image: 'erigon.avado.dappnode.eth:0.0.3'
    restart: always
    volumes:
      - 'data:/home/erigon'
    environment:
      - NETWORK=mainnet
      - EXTRA_OPTS=
    ports:
      - '30309:30309'
      - '30309:30309/udp'
volumes:
  data: {}
